name: Bundle

on:
  push:
    branches: ['release']

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build artifact
      run: mvn package
    
    - name: Upload artifact to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: torquescout
        path: target/TorqueScout*
              
      
